### PR TITLE
adding appveyor config

### LINKED ISSUE #5: add appveyor
@maxcnunes can you look at those errors, please? https://ci.appveyor.com/project/luisrudge/sqlectron-core
 It's on my username now so I don't flood your repo with changes. once it's working I'll open a PR

### PR DESCRIPTION
**Pull request by luisrudge**
It's testing postgres and mysql

I tested here: https://ci.appveyor.com/project/luisrudge/sqlectron-core

fix #5

### CODE REVIEW

**Comment by luisrudge** [comment]
image

Hell yeah

**Comment by maxcnunes** [comment]
Awesome! 

I just need to ask you one change. It is weird but the environment variable `<DB>_PORT` (e.g. `MYSQL_PORT`) actually contains the address (e.g. `MYSQL_PORT=tcp://172.17.0.12:3306`). It is a environment variable "injected" by the docker link. So could you replace the envs `<DB>_HOST` and `<DB>_PORT` with this approach `<DB>_PORT=tcp://<HOST>:<PORT>`?

This way you can also undo the changes on `spec/databases/config.js`.

Thanks,

**Comment by luisrudge** [comment]
Ops, sorry! I didn't know it was being set inside docker. I actually searched for the variable name but couldn't find it. I'll do those changes.

**Comment by luisrudge** [comment]
Done!

**Pull request merged**
